export const timeZones = [
  { name: "UTC", value: "UTC" },
  { name: "America/Barbados", value: "America/Barbados" },
  { name: "America/Bogota", value: "America/Bogota" },
  { name: "America/Los Angeles", value: "America/Los_Angeles" },
  { name: "America/Port of Spain", value: "America/Port_of_Spain" },
  { name: "America/Toronto", value: "America/Toronto" },
  { name: "America/New York", value: "America/New_York" },
  { name: "Asia/Beirut", value: "Asia/Beirut" },
  { name: "Asia/Dubai", value: "Asia/Dubai" },
  { name: "Asia/Manila", value: "Asia/Manila" },
  { name: "Asia/Singapore", value: "Asia/Singapore" },
  { name: "Asia/Tokyo", value: "Asia/Tokyo" },
  { name: "Europe/Berlin", value: "Europe/Berlin" },
  { name: "Europe/Paris", value: "Europe/Paris" },
  { name: "Europe/Madrid", value: "Europe/Madrid" },
  { name: "Europe/Lisbon", value: "Europe/Lisbon" },
  { name: "Europe/London", value: "Europe/London" },
  { name: "Europe/Bratislava", value: "Europe/Bratislava" },
  { name: "Europe/Amsterdam", value: "Europe/Amsterdam" },
];
